#! /bin/sh

#Define startup applications
pgrep -x sxhkd > /dev/null || sxhkd &
feh --bg-fill $HOME/Pictures/wallpapers/neon_shallows.png &
wal -i $HOME/Pictures/wallpapers/neon_shallows.png &
$HOME/.config/polybar/launch.sh &
xsetroot -cursor_name left_ptr &
#picom --experimental-backends --config $HOME/.config/picom/picom.conf --backend glx &

#Define Workspace Rules
#bspc monitor -d I II III IV V VI VII VIII IX X
bspc monitor -d 一 二 三 四 五 六
#七 八 九 十

#Define window settings
bspc config border_width         2
bspc config window_gap           6    #12
bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true

#After the -a you need to use the CLASS NAME to find out what it is so you can have the app follow the scheme, use xprop on the terminal.
bspc rule -a kitty desktop='^1' follow=on focus=on
bspc rule -a firefox desktop='^2' follow=on state=floating
#bspc rule -a Screenkey manage=off

#bspc config -d 二 window_gap 0

#Use Pywal on bspwm
#source the colors.
. "${HOME}/.cache/wal/colors.sh"

#Set the border colors.
bspc config normal_border_color "$color1"
bspc config active_border_color "$color2"
bspc config focused_border_color "$color15"
bspc config presel_feedback_color "$color1"
